name: Push Image

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # Run on the first of the month

env:
  IMAGE_NAME: sftp-ldap

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=latest
          tags: crobibero/sftp-ldap:latest